broker: &broker_connection
  solace_dev_mode: true

models:
  general: &general_model
    name: ${LLM_SERVICE_GENERAL_MODEL_NAME,openai/zai-glm-4.7}
    model_type: openai
    model_config:
      timeout_sec: 60

shared_settings:
  artifact_service: &default_artifact_service
    type: in_memory
    max_size_mb: 50
